services:
  app:
    image: matsu:latest
    volumes:
      - sqlite_data:/data/db
    environment:
      - DATABASE_FILE=/data/db/matsu.sqlite
      - DATABASE_URL=file:///data/db/matsu.sqlite
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
    ports:
      - "3000:3000"  # Expose your application port

volumes:
  sqlite_data:  # Define the volume
