services:
  init-db:
    build:
      context: .
      target: deps
    volumes:
      - sqlite_data:/data/db
    command: bunx drizzle-kit push
    environment:
      - DATABASE_URL=file:///data/db/matsu.sqlite
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}

  app:
    image: matsu:latest
    depends_on:
      - init-db
    volumes:
      - sqlite_data:/data/db
    environment:
      - DATABASE_URL=file:///data/db/matsu.sqlite
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
    ports:
      - "3000:3000"  # Expose your application port

volumes:
  sqlite_data:  # Define the volume
