name: Build and Push Docker Image to GitHub Container Registry

on:
  release:
    types:
      - published
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/matsu:${{ github.sha }} .
    
    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/matsu:${{ github.sha }}

    - name: Tag image with release version
      run: |
        docker tag ghcr.io/${{ github.repository_owner }}/matsu:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/matsu:${{ github.event.release.tag_name }}

    - name: Push release tag
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/matsu:${{ github.event.release.tag_name }}
